### ISSUE TITLE
How to get the pose of the 3D tracked object

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_object_analytics#33]
I need to track the objects, select one, get the pose of that object. Is it possible to achieve this? If yes, then how?

**Comment by Peter9606** [comment]
Sorry, current it’s not possible to get the pose.

**Comment by fiorano10** [comment]
Then what does it publish in object localization in 3D camera coordination system? What about using the [ros_moving_object](https://github.com/intel/ros_moving_object) to get the pose?

**Comment by fiorano10** [comment]
Okay, are you aware of any package which would allow to get the pose of the tracked object using a RealSense D400 series?

**Comment by Peter9606** [comment]
Sorry, I don't know about that. If not emergent, I can create a branch for your needs personally, but it will take time.

**Comment by fiorano10** [comment]
That sounds awesome! How much time though?

**Comment by fiorano10** [comment]
Could you tell me how you'd approach it to get the pose, so I'm able to work on it as well, and keep you updated of the progress.

**Comment by Peter9606** [comment]
The solution coming out of my head is to leverage PCL's pose estimation feature (i.e. the one described [here](http://pointclouds.org/documentation/tutorials/alignment_prerejective.php) ). The extra information that object analytics needs to provide is to compute "feature" for each object. It's the client's  (your program) responsibility to call PCL's estimation API to compute the pose.
What do you think?

**Comment by Peter9606** [comment]
I'm afraid I don't get you. Do you mean that you need all the points ?

**Comment by fiorano10** [comment]
Can I use this data, and tf to get the pose?
`sensor_msgs/RegionOfInterest roi      # region of interest
geometry_msgs/Point32 min             # min and max locate the diagonal of a bounding-box of the detected object whose
geometry_msgs/Point32 max             # x, y and z axis parellel to the axises correspondingly in camera coordinates`

**Comment by Peter9606** [comment]
According to my limited knowledge, I don't think so. You may also provide your patch if you have any idea.

**Comment by fiorano10** [comment]
Working on the patch, will keep you updated.

**Comment by Peter9606** [comment]
Great!
