### ISSUE TITLE
Error while running object_analytics_visualization

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_object_analytics#35]
[ERROR] [1523566355.826739]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566356.224998]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566356.492508]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566356.884548]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566357.216145]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566357.401567]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566357.913179]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566358.605716]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566359.402919]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566359.846018]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566360.136498]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566361.290347]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566362.081440]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566362.820419]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566363.481946]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566363.949358]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566364.556084]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566365.487441]: 'module' object has no attribute 'LINE_AA'
[ERROR] [1523566366.536286]: 'module' object has no attribute 'LINE_AA'

**Comment by Peter9606** [comment]
could you execute
```bash
python -c "import cv2;cv2.LINE_AA"
```
and see the result?

**Comment by fiorano10** [comment]
Output:
 `cv2.LINE_AA`
Traceback (most recent call last):
`  File "<stdin>", line 1, in <module>`
`AttributeError: 'module' object has no attribute 'LINE_AA'`

**Comment by Peter9606** [comment]
Probably you didn’t install OpenCV correctly. You should check with that.
