### ISSUE TITLE
A run_depend should be pcl_ros in package.xml

### ISSUE THREAD

**Issue by testkit** [intel/ros_object_analytics#36]
package.xml, line 53, 
    <run_depend>ros_pcl</run_depend> 
Should it be pcl_ros?

**Comment by Peter9606** [comment]
Fixed in https://github.com/intel/ros_object_analytics/commit/dbc5dbdd9a88a48bf7d2984d1fbcf7d81d8fdd63

**Comment by Peter9606** [comment]
@testkit  could you please confirm with this?

**Comment by testkit** [comment]
Thanks for quick fix, close this issue.
