### ISSUE TITLE
Movidius analytics launch doesn't publish all topics

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_object_analytics#37]
I'm running a single movidius with a D435 on Ubuntu 16.04 i7-5550U (2-core), 8GB RAM, when I run the analytics_opencl_caffe.launch, it publishes all the topics

`/object_analytics/detection`
`/object_analytics/localization`
`/object_analytics/pointcloud`
`/object_analytics/rgb`
`/object_analytics/segmentation`
`/object_analytics/tracking`

But when I launch analytics_movidius_ncs.launch, I get some of the topics being published, after rerunning the launch file multiple times, I get all the topics published. Do I need to add more NCS? Or could it be something else?

**Comment by Peter9606** [comment]
I have seen that issue many times, you should re-plug in the ncs device and re-launch object analytics again.

**Comment by fiorano10** [comment]
Okay, but is there a fix coming? Or is there a workaround? Hardware reset maybe?

**Comment by Peter9606** [comment]
Next time see the issue, please paste the log out, so I can figure out which issue it is.

**Comment by fiorano10** [comment]
There is no printed issue, it just doesn't publish some of the topics. I saw the rqt_console, there is nothing published in ROS_INFO/WARN/ERROR either.

**Comment by Peter9606** [comment]
It might be a different issue, can you reproduce it by launch ros movidius ncs only?

**Comment by fiorano10** [comment]
I just launch 
`realsense_ros_camera rs_rgbd.launch`
and
`analytics_movidius_ncs.launch`

**Comment by fiorano10** [comment]
1. If I use ros_opencl_caffe as backend, then no. It publishes all the topics everytime.
2. I will test this tomorrow afternoon, and update you

**Comment by Peter9606** [comment]
@fiorano10 , truly sorry, I gave you a wrong link which is pointing to classification rather than detection. would you please do it again using  "mobilenetssd" described in ["Detection for Video" ](https://github.com/intel/ros_intel_movidius_ncs/blob/master/doc/video_detection.md#mobilenet_ssd)

**Comment by fiorano10** [comment]
@Peter9606 , I tried running just the detection, and it published the topics /classified_objects, and /detected_objects, but there were no msgs being published on the topic. Also the image viewer doesn't open.

**Comment by Peter9606** [comment]
Can you log an issue under ros_intel_movidius_ncs project?

**Comment by Peter9606** [comment]
Can you give me a snapshot of rqt_graph?

**Comment by fiorano10** [comment]
Here you go [rqt_graph(img)](https://drive.google.com/open?id=1aCrG8GSYqPLvRZ8kZvFGO99fAUbwImBM) and [rqt_graph(svg)](https://drive.google.com/open?id=11ezACMiYFc5Pnb3oVJIgMKxrAAkUV4C3)

**Comment by fiorano10** [comment]
@Peter9606
Also, I’m running 2 Movidius, what should be the running frequency for Detection, Tracking, and Localization?

**Comment by Peter9606** [comment]
@fiorano10 
Movidius only accelerates the performance of detection. Currently detection and localization(actually it's segmentation) are the bottle neck of the overall performance, ant they are at the same FPS. Increasing Movidius can improve the performance of detection & tracking but doesn't help localization(segmentation) at all.

**Comment by fiorano10** [comment]
@Peter9606 
Right now running the object_analytics launch doesn't seem to care about the no. of Movidius, and runs at about 6-7 FPS. But at rare instances, the detection runs @20 FPS, tracking @10 FPS, and the localization @~6-7 FPS. Does it make sense?

**Comment by Peter9606** [comment]
Per my understanding, the PointCloudLibrary which is used to segment point cloud doesn't lie on multi-cpu or multi-core, so as long as the CPU clock rate approaches, the result won't change too much. 
It isn't official record, but I got pretty same FPS using Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz as Intel(R) Xeon(R) CPU E3-1275 v5 @3.60GHz recorded in [readme](https://github.com/intel/ros_object_analytics#kpi-of-differnt-detection-backends).

**Comment by fiorano10** [comment]
@Peter9606 
Any update on the topics not being published issue? The results in the readme are based on using 1 Movidius, right?

**Comment by Peter9606** [comment]
>  The results in the readme are based on using 1 Movidius, right?

Correct.

> Any update on the topics not being published issue? 
I think ros_movidius_ncs maintainer is working on this.

**Comment by fiorano10** [comment]
When I run the `movidius_ncs_detection` with 2 Movidius NCS it runs at 20HZ. But when I launch the `analytics_movidius_ncs.launch ` in Object Analytics, it runs at 10HZ irrespective of the no. of NCS connected.

**Comment by Peter9606** [comment]
@fiorano10  do you still see the issues described in this thread ?

**Comment by fiorano10** [comment]
Not anymore, thanks @Peter9606  👍
