### ISSUE TITLE
Frequency drop when running movidius_detection_ncs_camera vs analytics movidius

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_object_analytics#39]
The movidius detection run rs_camera.launch while the object_analytics uses rs_rgbd.launch which causes the drop in frame rate. When I run the movidius_ncs_detection with 2 Movidius NCS it runs at 20HZ. But when I launch the analytics_movidius_ncs.launch in Object Analytics, it runs at 10HZ irrespective of the no. of NCS connected.

**Comment by Peter9606** [comment]
@fiorano10 , what I observed is that both w/ and w/o object_analytics, NCS doesn't always run in a certain frame rate, sometime it run in 18 Hz, and sometime down to 9 Hz. I also checked with object_analytics code, and confirmed that there's no such logic could interfere NCS frame rate.
So could you please check again if that's your case too?

**Comment by Peter9606** [comment]
@fiorano10  I confirmed with ros_movidius_ncs maintainer and source code that if you want to accelerate the FPS of processing image from one camera, then using two Movidius NCS doesn't help.
