### ISSUE TITLE
 /object_analytics/tracking topic is not published.

### ISSUE THREAD

**Issue by MengNan-Li** [intel/ros_object_analytics#40]
(1)roslaunch astra_launch astra.launch
(2)roslaunch object_analytics_launch analytics_opencl_caffe.launch
(3)roslaunch object_analytics_visualization rviz.launch
/object_analytics/detection and /object_analytics/localization topic have data, but /object_analytics/tracking topic not has data. So, Rviz can't show correctly. 
What's the problem, How I can solve it.
Thinks a lot.

**Comment by Peter9606** [comment]
@MengNan-Li  Can you please also check if the other topics that object_analytics might publish are being published or not?
/object_analytics/rgb
/object_analytics/pointcloud
/object_analytics/detection
/object_analytics/segmentation
/object_analytics/localization

**Comment by MengNan-Li** [comment]
@Peter9606 Yes, These topics are all published, just not /object_analytics/tracking topic

**Comment by MengNan-Li** [comment]
@Peter9606 I can see the Point Clound, but can't see the 3D bounding box showing in Rviz. I meet the same problem when I use RealSense D415.

**Comment by Peter9606** [comment]
Can you confirm with the content of  /object_analytics/localization topic using "rostopic echo" command? See if there is something that can be localized in 3d.

**Comment by MengNan-Li** [comment]
There is nothing in "rostopic echo  /object_analytics/localization"

**roslaunch realsense_ros_camera rs_camera.launch**
[ INFO] [1526437222.215124294]: Initializing nodelet with 8 worker threads.
[ INFO] [1526437223.012392265]: RealSense ROS v2.0.2
[ INFO] [1526437223.012470903]: Running with LibRealSense v2.11.0
[ INFO] [1526437223.241825576]: getParameters...
[ INFO] [1526437223.275371661]: setupDevice...
[ INFO] [1526437223.275406134]: JSON file is not provided
[ INFO] [1526437223.275422586]: ROS Node Namespace: camera
[ INFO] [1526437223.275443880]: Device Name: Intel RealSense D415
[ INFO] [1526437223.275457975]: Device Serial No: 805212060130
[ INFO] [1526437223.275470603]: Device FW version: 05.08.15.00
[ INFO] [1526437223.275484042]: Device Product ID: 0AD3
[ INFO] [1526437223.275498241]: Enable PointCloud: Off
[ INFO] [1526437223.275511072]: Align Depth: Off
[ INFO] [1526437223.275525194]: Sync Mode: Off
[ INFO] [1526437223.275580109]: Device Sensors: 
[ INFO] [1526437223.275608692]: Stereo Module was found.
[ INFO] [1526437223.275623360]: RGB Camera was found.
[ INFO] [1526437223.275662991]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1526437223.275677086]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1526437223.275688266]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1526437223.275700471]: setupPublishers...
[ INFO] [1526437223.704991460]: setupStreams...
[ INFO] [1526437223.709646358]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1526437223.709909692]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1526437223.710160622]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1526437223.713321932]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1526437223.722849398]: publishStaticTransforms...
[ INFO] [1526437223.723334769]: RealSense Node Is Up!

**roslaunch object_analytics_launch analytics_opencl_caffe.launch**
........
I0516 10:20:37.300688  5819 net.cpp:266] This network produces output detection_out
I0516 10:20:37.300709  5819 net.cpp:280] Network initialization done.
I0516 10:20:37.300725  5819 net.cpp:281] Memory required for data: 86785584
[ INFO] [1526437240.549977903]: Load resources completely!

 **roslaunch object_analytics_visualization rviz.launch**


/object_analytics/rgb  : has messages
/object_analytics/pointcloud  : has messages
/object_analytics/detection  : has messages
/object_analytics/segmentation : has messages
/object_analytics/localization :  has not content.

**Comment by Peter9606** [comment]
I guess you would see something if a person stands in front of camera two meters away. Could you please give a try?

**Comment by MengNan-Li** [comment]
@Peter9606 I just have a try for your suggestion, but still have nothing in /object_analytics/localization. The   /object_analytics/detection topic show as follow:
    object: 
      object_name: "sheep"
      probability: 1.0
    roi: 
      x_offset: 196
      y_offset: 116
      height: 0
      width: 0
      do_rectify: False
No matter what in the front of the camera is human or object.

**Comment by Peter9606** [comment]
@MengNan-Li  It's weired to have value 0 for both "height" and "width", and that's the reason why there's no output from /object-analytics/localization. I think you should submit a bug to ros_opencl_caffe project

**Comment by MengNan-Li** [comment]
@Peter9606 Thinks for your help. :)
