### ISSUE TITLE
 fixed frame: camera_depth_optical_frame does not exist

### ISSUE THREAD

**Issue by ChampionRoy** [intel/ros_object_analytics#44]
When I launch rviz, here is a problem on global options, "no tf data. actual error:  fixed frame: camera_depth_optical_frame does not exist".
Do I miss something or set something wrong?

**Comment by Peter9606** [comment]
That means "camera_depth_optical_frame" topic isn't published by RGBD sensor, can you check if your RGBD sensor works or not?

**Comment by Peter9606** [comment]
@ChampionRoy do you mean the problem has been solved?

**Comment by yechun1** [comment]
@ChampionRoy seems you have found the solution. Just close the issue.
About the issue, you could also check the frame id that provided by Camera Sensor [example code](https://github.com/intel-ros/realsense/blob/ef2ee356fb26a49bf17662ff3b1c2f2a2157350c/realsense2_camera/include/constants.h#L80) and then choose the name from rviz.
